version: 2.1

orbs:
  node: circleci/node@1.1.6

# Job defaults
defaults: &defaults
  working_directory: ~/project
  executor:
      name: node/default

# Filters for jobs that only need to be run for a version tag (release)
only-release: &only-release
  filters:
    # Ignore all branches
    branches:
      ignore: /.*/
    # And only run on version tags
    tags:
      only: /^v.*/

# Filters for jobs that should not run for a version tag
only-non-release: &only-non-release
  filters:
    tags:
      ignore: /^v.*/

jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Build project
      - node/with-cache:
          steps:
            - run: 
                name: Install dependencies
                command: yarn
            - run: 
                name: Build
                command: yarn build
            - persist_to_workspace:
                root: ~/project
                paths:
                  - dist

  smoke-test:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Get the build artifacts
      - attach_workspace:
          at: ~/project
      
      # Run the smoke test (one TypeScript version only)
      - node/with-cache:
          steps:
            - run: 
                name: Test with TypeScript 3.1.1 (ES5)
                command: yarn test:version -v 3.1.1 -l es5
            - run: 
                name: Test with TypeScript 3.1.1 (ES6)
                command: yarn test:version -v 3.1.1 -l es6

  e2e-test:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Get the build artifacts
      - attach_workspace:
          at: ~/project
      
      # Run the smoke test (one TypeScript version only)
      - node/with-cache:
          steps:
            - run: 
                name: Test with all supported TypeScript versions (ES5)
                command: yarn test:versions -l es5
            - run: 
                name: Test with all supported TypeScript versions (ES6)
                command: yarn test:versions -l es6
            - run:
                name: Test examples
                command: yarn test:examples

  publish:
    <<: *defaults
    steps:
      # Checkout the project
      # - checkout

      # Get the build artifacts
      - attach_workspace:
          at: ~/project
      
      # Run the smoke test (one TypeScript version only)
      - node/with-cache:
          steps:
            - run:
                name: Authenticate for NPM
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > dist/.npmrc && cat dist/.npmrc
            - run:
                name: Publish package
                command: cd dist && npm publish

workflows:
  test:
    jobs:
      - build
      - smoke-test:
          requires:
              - build
  
  test-and-publish:
    jobs:
      - build:
          <<: *only-release
      
      - e2e-test:
          <<: *only-release
          requires:
              - build

      - publish:
          <<: *only-release
          type: approval
          requires:
              - e2e-test
              - build
