version: 2.1

orbs:
  node: circleci/node@1.1.6

# Job defaults
defaults: &defaults
  working_directory: ~/project
  executor:
      name: node/default

# Filters for jobs that only need to be run for a version tag (release)
only-release: &only-release
  filters:
    # Ignore all branches
    branches:
      ignore: /.*/
    # And only run on version tags
    tags:
      only: /^v(\d+)\.(\d+)\.(\d+).*/

# Filters for jobs that only need to be run for a version tag (release)
only-release-candidate: &only-release-candidate
  filters:
    # Ignore all branches
    branches:
      only: 
          - main
          - /^release-.*/

only-feature-branches: &only-feature-branches
  filters:
    branches:
      ignore:
          - main
          - /^release-.*/

jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Build project
      - node/with-cache:
          steps:
            - run: 
                name: Install dependencies
                command: yarn
            - run: 
                name: Build
                command: yarn workspace ts-type-checked run build
            - persist_to_workspace:
                root: ~/project
                paths:
                  - main/dist

  e2e-test:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Get the build artifacts
      - attach_workspace:
          at: ~/project
      
      # Run the smoke test (one TypeScript version only)
      - node/with-cache:
          steps:
            - run: 
                name: Test package & examples
                command: yarn test

  publish:
    <<: *defaults
    steps:
      # Checkout the project
      - checkout

      # Get the build artifacts
      - attach_workspace:
          at: ~/project
      
      # Run the smoke test (one TypeScript version only)
      - node/with-cache:
          steps:
            - run:
                name: Authenticate for NPM
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > main/dist/.npmrc
            - run:
                name: Publish package
                command: cd main/dist && npm publish

workflows:
  test:
    jobs:
      - build
      - e2e-test:
          requires:
              - build
  
  release:
    jobs:
      - build:
          <<: *only-release
      
      - e2e-test:
          <<: *only-release
          requires:
              - build

      - approve:
          <<: *only-release
          type: approval
          requires:
              - e2e-test

      - publish:
          <<: *only-release
          requires:
              - approve
